### ISSUE TITLE
ERROR: ec2_ami_find is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by matthieuchoplin** [atplanet/ansible-auto-scaling-tutorial#1]
Hi,

I stumbled upon your tutorial and tried it but found the following issue when I launched the command
`ansible-playbook deploy.yml -vv` with the version 1.9.x of ansible

```
$ ansible-playbook deploy.yml -vv -i ../learn-ansible/hosts 
ERROR: ec2_ami_find is not a legal parameter in an Ansible task or handler
```

It works well with the _version 2.0_ though since the parameter  ec2_ami_find has been implemented for the version 2.0.

Thanks for your tuto!

**Comment by manicminer** [comment]
@matthieuchoplin Many thanks for the report and the kind words! I'll add instructions on locally importing the module, and bump the tutorial to use 2.x after the first stable release.
