### ISSUE TITLE
some minor issues I had to patch

### ISSUE THREAD

**Issue by gmaruzz** [atplanet/ansible-auto-scaling-tutorial#4]
Ciao,

very very nice work, congratulations!

Eventually I made it to work, albeit it does not delete old AMIs and old LCs. For LCs is because I had to change the name of them from a variable one (webapp-timestamp) to a fixed one (webapp), because with the variable name the creation of autoscaling group does not work (because it requires the name of the launch config).

I will try to fix that too, as time permit.

Tested with ansible 1.9.4 Python 2.7.9

I attach a git diff and app.js file (app.js because it does not need express framework).

Can you have a look at the diff and let me know your comments?

-giovanni
attachments follow:

<pre>

============================================
// Load the http module to create an http server.
var http = require('http');

// Configure our HTTP server to respond with Hello World to all requests.
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");
});

// Listen on port 8000, IP defaults to 127.0.0.1
server.listen(8000);

// Put a friendly message on the terminal
console.log("Server running at http://127.0.0.1:8000/");
============================================

diff --git a/deploy.yml b/deploy.yml
index 765f69b..02aac42 100644
--- a/deploy.yml
+++ b/deploy.yml
@@ -26,11 +26,11 @@
   connection: local
   gather_facts: no
   roles:
-    - create-ami
+    - build-ami
     - create-launch-configuration
     - load-balancer
     - auto-scaling
-    - dns
+#    - dns

 - hosts: localhost
   connection: local
diff --git a/group_vars/all.yml b/group_vars/all.yml
index 7eb859f..df61994 100644
--- a/group_vars/all.yml
+++ b/group_vars/all.yml
@@ -1,14 +1,15 @@
 ---
 # group_vars/all.yml
-
-region: us-east-1
-zone: us-east-1a
-keypair: YOUR_KEYPAIR
-security_groups: YOUR_SECURITY_GROUP
+ansible_ssh_user: ubuntu
+region: eu-west-1
+zone: eu-west-1a
+keypair: audiens-01
+#security_groups: sg-a4774fc1
+security_groups: default
 instance_type: m3.medium
 volumes:
   - device_name: /dev/sda1
     device_type: gp2
     volume_size: 20
     delete_on_termination: true
-domain: YOUR_DOMAIN_NAME
+domain: "ciao.org"
diff --git a/roles/auto-scaling/tasks/main.yml b/roles/auto-scaling/tasks/main.yml
index a7f8cc4..4cf5d84 100644
--- a/roles/auto-scaling/tasks/main.yml
+++ b/roles/auto-scaling/tasks/main.yml
@@ -10,11 +10,17 @@
     asg_properties: "{{ (asg_properties_result.stdout | from_json).AutoScalingGroups[0] }}"
   when: (asg_properties_result.stdout | from_json).AutoScalingGroups | count

+- name: Set asg_properties variable from DEAD AIR output if the Auto Scaling Group NOT already exists
+  set_fact:
+    asg_properties: "{{ 0 }}"
+  when: not (asg_properties_result.stdout | from_json).AutoScalingGroups | count
+
+
 - name: Configure Auto Scaling Group and perform rolling deploy
   ec2_asg:
     region: "{{ region }}"
-    name: webapp
-    launch_config_name: webapp
+    name: "webapp"
+    launch_config_name: "webapp"
     availability_zones: "{{ zone }}"
     health_check_type: ELB
     health_check_period: 300
@@ -32,7 +38,7 @@
   ec2_scaling_policy:
     region: "{{ region }}"
     name: "{{ item.name }}"
-    asg_name: webapp
+    asg_name: "webapp"
     state: present
     adjustment_type: "{{ item.adjustment_type }}"
     min_adjustment_step: "{{ item.min_adjustment_step }}"
@@ -53,13 +59,14 @@

 - name: Determine Metric Alarm configuration
   set_fact:
+    asg_name: "webapp"
     metric_alarms:
-      - name: "{{ asg_name }}-ScaleUp"
+      - name: "webapp-ScaleUp"
         comparison: ">="
         threshold: 50.0
         alarm_actions:
           - "{{ sp_result.results[0].arn }}"
-      - name: "{{ asg_name }}-ScaleDown"
+      - name: "webapp-ScaleDown"
         comparison: "<="
         threshold: 20.0
         alarm_actions:
@@ -79,8 +86,8 @@
     evaluation_periods: 5
     unit: "Percent"
     dimensions:
-      AutoScalingGroupName: "{{ asg_name }}"
+      AutoScalingGroupName: "webapp"
     alarm_actions: "{{ item.alarm_actions }}"
   with_items: metric_alarms
-  when: max_size > 1
+  when: 10 > 1
   register: ma_result
diff --git a/roles/create-launch-configuration/tasks/main.yml b/roles/create-launch-configuration/tasks/main.yml
index d535c2b..4cb6aca 100644
--- a/roles/create-launch-configuration/tasks/main.yml
+++ b/roles/create-launch-configuration/tasks/main.yml
@@ -4,7 +4,8 @@
 - name: Create Launch Configuration
   ec2_lc:
     region: "{{ region }}"
-    name: "webapp-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
+#    name: "webapp-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
+    name: "webapp"
     image_id: "{{ ami.image_id }}"
     key_name: "{{ keypair }}"
     instance_type: "{{ instance_type }}"
diff --git a/roles/deploy/tasks/main.yml b/roles/deploy/tasks/main.yml
index a54fbb2..b6b0023 100644
--- a/roles/deploy/tasks/main.yml
+++ b/roles/deploy/tasks/main.yml
@@ -7,24 +7,36 @@
     state: present
   sudo: yes

+- name: Install node.js
+  apt:
+    pkg: nodejs
+    state: present
+  sudo: yes
+
+- name: Install nodejs-legacy
+  apt:
+    pkg: nodejs-legacy
+    state: present
+  sudo: yes
+
 - name: Create www directory
   file:
-    path: /srv/www
+    path: /srv/www/webapp
     owner: ubuntu
     group: ubuntu
     state: directory
   sudo: yes

-- name: Clone repository
-  git:
-    repo: "https://github.com/atplanet/hello-world-express-app.git"
-    dest: /srv/www/webapp
-    version: master
+- name: Install app.js
+  copy:
+    src: app.js
+    dest: /srv/www/webapp/app.js
+  sudo: yes

 - name: Install upstart script
   copy:
     src: upstart.conf
-    dest: /etc/upstart/webapp.conf
+    dest: /etc/init/webapp.conf
   sudo: yes

 - name: Enable and start the application
diff --git a/roles/nginx/files/nginx.conf b/roles/nginx/files/nginx.conf
index 22e6ef5..a402e55 100644
--- a/roles/nginx/files/nginx.conf
+++ b/roles/nginx/files/nginx.conf
@@ -1,4 +1,4 @@
-/nginx/files/nginx.conf
+# roles/nginx/files/nginx.conf

 server {
   listen 80 default_server;
diff --git a/roles/nginx/tasks/main.yml b/roles/nginx/tasks/main.yml
index 73256fd..187ddb6 100644
--- a/roles/nginx/tasks/main.yml
+++ b/roles/nginx/tasks/main.yml
@@ -10,7 +10,7 @@
 - name: Configure Nginx
   copy:
     src: nginx.conf
-    dest: /etc/sites-enabled/default
+    dest: /etc/nginx/sites-enabled/default
   sudo: yes

 - name: Enable and start Nginx

=======================================
</pre>

**Comment by manicminer** [comment]
@gmaruzz Many thanks for the patch (and kind words)! Sorry I hadn't time to look at this before now, but will do soon.

**Comment by kazysgurskas** [comment]
> For LCs is because I had to change the name of them from a variable one (webapp-timestamp) to a fixed one (webapp), because with the variable name the creation of autoscaling group does not work (because it requires the name of the launch config).

You could retain timestamp format by using ansible's `set_fact` module:

``` yaml
- set_fact:
    lc_name: "webapp-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"

- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "{{ lc_name }}"
    image_id: "{{ ami.image_id }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    volumes: "{{ volumes }}"
    instance_monitoring: yes
```

The `lc_name` variable will survive between plays, so you can use it when creating the autoscaling group as `launch_config_name`.

**Comment by manicminer** [comment]
Wow, another long stretch and a sadly forgotten issue.

@gmaruzz Thanks again for taking the time to send your patch. I'm still not certain about the issue you described using variable launch config names, that pattern has always worked for me. However, many of the Ansible AWS modules have received a lot of love in version 2.0 / 2.1 and we'll be updating the tutorial for Ansible 2 soon, which should also clear up the issue you had when an auto-scaling-group didn't already exist.
