### ISSUE TITLE
playbook is failing 

### ISSUE THREAD

**Issue by babatundebusari** [atplanet/ansible-auto-scaling-tutorial#6]
I am getting this error when playbook is launched

```
ASK [launch : Launch new instance] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The following group names are         
not valid: sg-xxxxxx"}
```

What is the hint for the security group here? must the security group be for the EC2-classic platform or it can be EC2-VPC platform as well?
Any more information needed to understand what SG to insert?

Thanks

**Comment by kbroughton** [comment]
This isn't a great error message.  You might think it means that the name you supplied doesn't comply with formatting rules.  It really means the name you are looking for is not found.

from ec2.py
  890 
  891     try:
  892         # Here we try to lookup the group id from the security group name - if group is set.
  893         if group_name:
  894             if vpc_id:
  895                 grp_details = ec2.get_all_security_groups(filters={'vpc_id': vpc_id})
  896             else:
  897                 grp_details = ec2.get_all_security_groups()
  898             if isinstance(group_name, basestring):
  899                 group_name = [group_name]
  900             unmatched = set(group_name).difference(str(grp.name) for grp in grp_details)
  901             if len(unmatched) > 0:
  902                 module.fail_json(msg="The following group names are not valid: %s" % ', '.join(unmatched))
  903             group_id = [ str(grp.id) for grp in grp_details if str(grp.name) in group_name ]
  904         # Now we try to lookup the group id testing if group exists.

**Comment by Dawny33** [comment]
@babatundebusari You need to specify `group_id: sg-xxxxxx` in case you are using a single security group.

**Comment by dayanand33** [comment]
I encountered the same error and it turned out that the ami id specified in the playbook should belong to the specified region. https://aws.amazon.com/amazon-linux-ami/
I wish aws gave a more meaningful error in such cases
